pipeline {
   agent any
   environment{
    SCANNER_HOME= tool "sonar-scanner"
   }
      stages{
         stage('checkout'){
               steps{
                 git changelog: false, credentialsId: 'new-github-token', poll: false, url: 'https://github.com/medinahakinsowon/Ibt-maven.git'
               }
         }
         stage('Validate'){
              steps{
                 sh 'mvn validate'
              }
         }
         stage('compile'){
               steps{
                  sh 'mvn compile'
               }
         }
         stage('test'){
               steps{
                  sh 'mvn test'
               }
         }
         stage('package'){
                steps{
                  sh 'mvn package'
                }
         }
         stage('owasp-scan'){
              steps{
                 dependencyCheck additionalArguments:'--scan ./ ',odcInstallation:"OWASP-dependency-check"
                 dependencyCheckPublisher pattern: "**/dependency-check-report.xml"
              }
         }
          stage('sonarqube'){
                steps{
                    withSonarQubeEnv('sonar-server'){
                               '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Ibt-maven\
                                     -Dsonar.java.binaries= \
                                     -Dsonar.analysis.mode=
                                     -Dsonar.host.url=http://localhost:9000
                                     -Dsonar.projectKey=Ibt-maven -Dsonar.sources=.'''\
                    }
                }
           }


      }

   }


