pipeline {
   agent any
      stages{
         stage('Validate'){
              steps{
                 sh 'mvn validate'
              }
         }
         stage('compile'){
               steps{
                  sh 'mvn compile'
               }
         }
         stage('test'){
               steps{
                  sh 'mvn test'
               }
         }
         }

      }


